# Generated by Django 5.1.1 on 2025-01-31 19:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ordertickets',
            fields=[
                ('ticket_id', models.AutoField(primary_key=True, serialize=False, verbose_name='شماره تیکت')),
                ('buyer_namelastname', models.CharField(max_length=30, verbose_name='نام خریدار')),
                ('buyer_phone', models.CharField(max_length=15, verbose_name='شماره تلفن')),
                ('request_title', models.CharField(max_length=20, verbose_name='عنوان درخواست')),
                ('request_discription', models.CharField(max_length=150, verbose_name='متن درخواست')),
                ('ticket_time', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ سفارش')),
            ],
        ),
        migrations.CreateModel(
            name='products',
            fields=[
                ('pistachio_id', models.AutoField(primary_key=True, serialize=False)),
                ('pistachio_name', models.CharField(max_length=20)),
                ('pistachio_photo', models.ImageField(upload_to='prdphotos', verbose_name='pstachio-photo')),
                ('pistachio_status', models.CharField(max_length=20)),
                ('pistachio_per_ounce', models.IntegerField()),
                ('pistachio_quality', models.CharField(max_length=15)),
                ('pistachio_price', models.FloatField()),
                ('pistachio_gain_status', models.BooleanField(default=False)),
                ('pistachio_gain', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='buytickets',
            fields=[
                ('ticket_id', models.AutoField(primary_key=True, serialize=False, verbose_name='شماره تیکت')),
                ('buyer_namelastname', models.CharField(max_length=30, verbose_name='نام خریدار')),
                ('buyer_phone', models.CharField(max_length=20, verbose_name='شماره تلفن')),
                ('gain_product', models.FloatField(verbose_name='مقدار (به کیلو)')),
                ('order_discription', models.CharField(blank=True, max_length=400, null=True, verbose_name='توضیحات سفارش')),
                ('calculated_price', models.FloatField(verbose_name='قیمت نهایی')),
                ('ticket_time', models.DateTimeField(auto_now=True, verbose_name='تاریخ سفارش')),
                ('pistachio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.products', verbose_name='محصول سفارش داده شده')),
            ],
        ),
    ]
