# Generated by Django 5.1.1 on 2025-02-12 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='buytickets',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ordertickets',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
    ]
